version: "3.8"

services:
  backend:
    build:
      context: ./atta-chakki
      dockerfile: Dockerfile
    container_name: spring-backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    build:
      context: ./flourmill_front
      dockerfile: Dockerfile
    container_name: angular-frontend
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: attachakki
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
